# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
                ('itemNo', models.CharField(max_length=30)),
                ('itemDescription', models.CharField(max_length=45)),
                ('itemGroup', models.CharField(max_length=50)),
            ],
        ),
    ]
