# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPApp', '0002_auto_20171005_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='ItemMaster',
            new_name='Item_Master',
        ),
    ]
