# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPApp', '0003_auto_20171006_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_master',
            name='subId',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='item_master',
            name='unit',
            field=models.IntegerField(default=55),
        ),
    ]
