# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPApp', '0004_auto_20171006_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_master',
            name='catId',
            field=models.IntegerField(default=100),
        ),
    ]
