# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPApp', '0005_item_master_catid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_master',
            name='refUnit',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='unit',
            field=models.IntegerField(default=50),
        ),
    ]
