# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERPApp', '0006_auto_20171006_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item_Category',
        ),
    ]
