# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPApp', '0007_delete_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCategory', models.CharField(max_length=90)),
            ],
        ),
        migrations.RemoveField(
            model_name='item_master',
            name='refUnit',
        ),
        migrations.RemoveField(
            model_name='item_master',
            name='unit',
        ),
    ]
