# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPApp', '0008_auto_20171007_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemSubCategory', models.CharField(max_length=100)),
            ],
        ),
    ]
